### PR TITLE
replace "DEL" Commands with "UNLINK".

### PR DESCRIPTION
**Pull request by jonashrem**
Implements #158 

This PR replaces DEL Command with UNLINK command like I suggested in #158 

Details about UNLINK can be found here  https://redis.io/commands/unlink .

As noticed here https://github.com/redis/redis/issues/1748#issuecomment-43233084  this will not change the behavior.

As there is no check of Redis version included, it will break Redis Versions < 4.0 through.

As Redis 4.0 was released on 2017-07-14 and Redis 3 went EOL with the Redis 5 on 2018-10-17, I don't expect this being an issue.

### CODE REVIEW

**Review by colinmollenhour — CHANGES_REQUESTED** [review]
Thanks for the PR!

Changing the lua scripts requires updating the LUA_CLEAN_SH1 and LUA_GC_SH1 contants, though. It's been forever since I've had to do this.. @nemphys, what is your process for obtaining the new script hashes?

**Comment by nemphys** [comment]
@colinmollenhour not anything fancy, I just add a temporary
Mage::log(sha1($script));
right after the script assignment line and copy it from the log.

**Comment by colinmollenhour** [comment]
Finally merged! Sorry it took over 2 years...

**Comment by jonashrem** [comment]
Thanks. I think we can close #158 than as well

**Pull request merged**
